# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
    - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
    - checkout

    # Create folder for test results.
    - run:
        name: create test result folder
        command: |
          mkdir test-reports

    # Download and cache dependencies.
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements/requirements.txt" }}
        # Fallback to using the latest cache if no exact match is found.
        - v1-dependencies-

    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements/requirements.txt

    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "requirements/requirements.txt" }}

    # Run tests! We use pytest's test-runner (https://pytest.org)
    - run:
        name: run tests
        command: |
          . venv/bin/activate
          pytest -v > test-reports/pytest.log


    # Store test results.
    - store_artifacts:
        path: test-reports
        destination: test-reports
